parameters:
  - name: environment
    type: string
    default: ""
  - name: azureSubscription
    type: string
    default: ""
  - name: artifactName
    type: string
    default: ""
  - name: resourceGroupName
    type: string
    default: ""

stages:
  #- ${{ if eq(parameters.environment, 'dev') }}:
  - stage: Deploytodev
    condition: eq('${{parameters.environment}}', 'dev')
    jobs:
    - deployment: DeployWebdev
      displayName: deploy Web App Dev
      environment: ${{parameters.environment}}
      strategy:
        runOnce:
          deploy:
            steps:
              - pwsh: Write-Host "DEV enviornment and user entered environment name is ${{parameters.environment}}"

  - stage: Deploytoqa
    condition: eq(${{parameters.environment}}, 'qa')
    jobs:
    - deployment: DeployWebqa
      displayName: deploy Web App Qa
      environment: ${{parameters.environment}}
      strategy:
        runOnce:
          deploy:
            steps:
              - pwsh: Write-Host "QA enviornment and user entered environment name is ${{parameters.environment}}"
  #- ${{ if eq(parameters.environment, 'test') }}:
  - stage: Deploytotest
    condition: eq(${{parameters.environment}}, 'test')
    jobs:
    - deployment: DeployWebtest
      displayName: deploy Web App Test
      environment: ${{parameters.environment}}
      strategy:
        runOnce:
          deploy:
            steps:
              - pwsh: Write-Host "Test enviornment and user entered environment name is ${{parameters.environment}}"