name: $(Build.DefinitionName)-$(Build.Reason)

resources:
 pipelines:
   - pipeline: prodpipeline
     source: template-test-deploy
     trigger:
      branches:
       include:
         - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: prodenv
    value: prod
  - name: buildConfiguration
    value: 'Release'
  - name: dotnetSdkVersion
    value: '6.x'
  - name: azureSubscription
    value: MyAzureServiceConnection

stages:
- template: build-template.yml
  parameters:
    buildConfiguration: ${{variables.buildConfiguration}}
    dotnetSdkVersion: ${{variables.dotnetSdkVersion}}

- template: deploy-template.yml
  parameters:
    buildConfiguration: ${{variables.buildConfiguration}}
    environment: ${{variables.prodenv}}
    azureSubscription: ${{variables.azureSubscription}}